# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_mining
      

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
