version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /var/lib/minio/data:/data
    environment:
      MINIO_ROOT_USER: nhatlinh 
      MINIO_ROOT_PASSWORD: nhatlinh
      # MINIO_SERVER_URL: https://minio.nhatlinh.ddns.net
      # MINIO_BROWSER_REDIRECT_URL: https://console.nhatlinh.ddns.net
    command: server --console-address ":9001" /data
    networks:
      - minio-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - minio
    networks:
      - minio-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"

networks:
  minio-net:
    driver: bridge